backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "./img"

collections:
  - name: "linktree_data"
    label: "Linktree Einstellungen"
    files:
      - file: "data.json"
        name: "data"
        label: "Inhalte bearbeiten"
        fields:
          - name: "profile"
            label: "Profil"
            widget: "object"
            fields:
              - {name: "name", label: "Anzeigename", widget: "string"}
              - {name: "description", label: "Beschreibung", widget: "text"}
              - {name: "image", label: "Profilbild", widget: "image"}
          
          - name: "socialIcons"
            label: "Kleine Social Media Icons"
            widget: "list"
            fields:
              - {name: "url", label: "Link URL", widget: "string"}
              - {name: "icon", label: "Icon Bild", widget: "image"}

          - name: "videoModule"
            label: "Video Highlight"
            widget: "object"
            fields:
              - {name: "isVisible", label: "Video-Block anzeigen?", widget: "boolean", default: true}
              - {name: "url", label: "Video URL", widget: "string"}
              - {name: "thumbnail", label: "Vorschaubild / Icon", widget: "image"}
              - {name: "title", label: "Titel (z.B. Neuestes Video)", widget: "string"}
              - {name: "subtitle", label: "Untertitel (z.B. YouTube)", widget: "string"}
              - {name: "buttonText", label: "Button Text", widget: "string"}

          - name: "links"
            label: "Deine großen Links"
            widget: "list"
            fields:
              - {name: "title", label: "Link Titel", widget: "string"}
              - {name: "url", label: "Link URL", widget: "string"}
              - {name: "icon", label: "Link Icon", widget: "image"}